version: '3'

services:
  backend:
    build: ./backend
    networks:
        - app-tier
    volumes:
      - ./backend:/backend
    ports:
      - "3000:3000"
    depends_on:
      - "db"
  db:
    image: mysql:8.0.23
    networks:
        - app-tier
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql:rw
      - ./user.sql:/docker-entrypoint-initdb.d/1.sql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: apnews
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.9
    ports:
      - 8000:80
    depends_on:
      - "db"
    environment:
      PMA_PASSWORD: 1234
      PMA_USER: root
      PMA_HOSTS: db
    networks:
        - app-tier
networks:
    app-tier:
        driver: bridge